DATA:
  data_root: /raid/workspace/loc_toy/dataset/cod 
  train_list: /raid/workspace/loc_toy/dataset/cod/COD_train/train.lst
  val_list: /raid/workspace/loc_toy/dataset/cod/CAMO_test/test.lst
  classes: 1

TRAIN:
  arch: mgl
  num_clusters: 32
  stage: 1 # 1: single stage learning, 2:recurrent learning
  layers: 50
  sync_bn: True  # adopt sync_bn or not
  train_h: 473
  train_w: 473
  scale_min: 0.5  # minimum random scale
  scale_max: 2.0  # maximum random scale
  rotate_min: -90 #-10  # minimum random rotate
  rotate_max: 90 #10  # maximum random rotate
  zoom_factor: 8  # zoom factor for final prediction during training, be in [1, 2, 4, 8]
  ignore_label: 0 # 255
  aux_weight: 0.4
  train_gpu: [0]
  workers: 16  # data loader workers
  batch_size: 3  # batch size for training
  batch_size_val: 36  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.00000001
  epochs: 200
  start_epoch: 0
  power: 0.9
  momentum: 0.9
  weight_decay: 0.0001
  manual_seed:
  print_freq: 20
  save_freq: 5
  save_path: exp/model
  weight:  
  resume: 
  evaluate:  True #False  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend

Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0
  use_apex: True
  opt_level: 'O0'
  keep_batchnorm_fp32:
  loss_scale:

TEST:
  test_list: /raid/workspace/loc_toy/dataset/cod/COD10K_test/test.lst
  split: val  # split in [train, val and test]
  base_size: 473  # based size for scaling
  test_h: 473
  test_w: 473
  scales: [1.0]  # evaluation scales, ms as [0.5, 0.75, 1.0, 1.25, 1.5, 1.75]
  test_batch_size: 1
  has_prediction: False  # has prediction already or not
  index_start: 0  # evaluation start index in list
  index_step: 0  # evaluation step index in list, 0 means to end
  test_gpu: [0] 
  model_path:  model_file/mgl_s.pth
  save_folder: exp/result/  # results save folder
